scss_files: 'themes/joshuagleitze.de/source/style/**/*.scss'

linters:
    BorderZero:
        convention: none

    DisableLinterReason:
        enabled: true

    EmptyLineBetweenBlocks:
        ignore_single_line_blocks: false

    Indentation:
        character: tab
        width: 1

    PrivateNamingConvention:
        enabled: true

    PropertySortOrder:
        separate_groups: true
        # The order is Concentric CSS, taken from
        # https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/concentric.txt to have group
        # separators.
        order:
            - display
            - position
            - top
            - right
            - bottom
            - left
            -
            - columns
            - column-gap
            - column-fill
            - column-rule
            - column-span
            - column-count
            - column-width
            -
            - float
            - clear
            -
            - transform
            - transition
            - animation
            - animation-name
            - animation-duration
            - animation-timing-function
            - animation-delay
            - animation-iteration-count
            - animation-direction
            - animation-fill-mode
            - animation-play-state
            -
            - visibility
            - opacity
            - z-index
            -
            - margin
            - margin-top
            - margin-bottom
            - margin-left
            - margin-right
            -
            - outline
            -
            - border
            - border-top
            - border-right
            - border-bottom
            - border-left
            - border-width
            - border-top-width
            - border-right-width
            - border-bottom-width
            - border-left-width
            - border-style
            - border-top-style
            - border-right-style
            - border-bottom-style
            - border-left-style
            - border-radius
            - border-top-left-radius
            - border-top-right-radius
            - border-bottom-left-radius
            - border-bottom-right-radius
            -
            - border-color
            - border-top-color
            - border-right-color
            - border-bottom-color
            - border-left-color
            -
            - box-shadow
            -
            - background
            - background-color
            - background-image
            - background-repeat
            - background-position
            - background-size
            - cursor
            -
            - padding
            - padding-top
            - padding-bottom
            - padding-left
            - padding-right
            -
            - box-sizing
            - width
            - min-width
            - max-width
            - height
            - min-height
            - max-height
            -
            - overflow
            -
            - list-style
            - caption-side
            - table-layout
            - border-collapse
            - border-spacing
            - empty-cells
            -
            - vertical-align
            - text-align
            - text-indent
            - text-transform
            - text-decoration
            - text-rendering
            - text-shadow
            - text-overflow
            - line-height
            - word-spacing
            - letter-spacing
            - white-space
            -
            - color
            - font
            - font-family
            - font-size
            - font-weight
            - font-smoothing
            - font-style
            -
            - content
            - quotes
        min_properties: 1

    SpaceAfterVariableColon:
        enabled: true

    TrailingZero:
        enabled: true

    TransitionAll:
        enabled: true
