apiVersion: apps/v1
kind: Deployment
metadata:
  name: studierlangsam-de
  namespace: studierlangsam
  labels:
    app: studierlangsam.de
spec:
  selector:
    matchLabels:
      app: studierlangsam.de
  template:
    metadata:
      name: studierlangsam-de
      labels:
        app: studierlangsam.de
    spec:
      containers:
        - name: studierlangsam-de
          image: ${IMAGE}
          ports:
            - containerPort: 80
              name: web
          readinessProbe:
            httpGet:
              path: /
              port: web
            timeoutSeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: web
            timeoutSeconds: 30
            periodSeconds: 15
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
      imagePullSecrets:
        - name: ghcr.io
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: studierlangsam-de
  namespace: studierlangsam
  labels:
    app: studierlangsam.de
spec:
  ports:
    - port: 80
      targetPort: web
      name: web
  selector:
    app: studierlangsam.de

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studierlangsam-de
  namespace: studierlangsam
  labels:
    app: studierlangsam.de
  annotations:
    cert-manager.io/cluster-issuer: live
    traefik.ingress.kubernetes.io/router.middlewares: ingress-https-redirect@kubernetescrd,ingress-sts@kubernetescrd
spec:
  rules:
    - host: studierlangsam.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studierlangsam-de
                port:
                  name: web
  tls:
    - secretName: studierlangsam-de-tls
      hosts:
        - studierlangsam.de
