name: Live Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Live
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Download npm Dependencies
        run: npm ci
      - name: Check
        run: npm run check
      - name: Build Release
        run: |
          npm run clean
          npm run build
          
      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Image Tag
        id: imageTag
        run: |
          echo "image=ghcr.io/studierlangsam/webseite:$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
      - name: Build and Push Container
        run: |
          docker build . -t $IMAGE
          docker push $IMAGE
        env:
          IMAGE: ${{ steps.imageTag.outputs.image }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3.2
        with:
          version: v1.23.1
      - name: Write Kubeconfig
        run: |
          echo "$KUBECONFIG_CONTENT" > "$KUBECONFIG"
        env:
          KUBECONFIG_CONTENT: ${{ secrets.DEPLOYMENT_KUBECONFIG }}
      - name: Deploy to Live
        run: |
          kubectl kustomize deployment/live |
          	envsubst '$IMAGE' |
          	kubectl apply -f - --prune --selector app=studierlangsam.de,version=live --prune-whitelist=apps/v1/Deployment --prune-whitelist=/v1/Service --prune-whitelist=networking.k8s.io/v1/Ingress
        env:
          IMAGE: ${{ steps.imageTag.outputs.image }}
      - name: Delete Kubeconfig
        if: always()
        run: |
          rm -f "$KUBECONFIG"
