name: Live Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Live
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Setup kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.23.1'
      - name: Install graphicsmagick
        run: |
          sudo apt-get update
          sudo apt-get install graphicsmagick
      - name: Download npm Dependencies
        run: npm ci
      - name: Log in to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Write Kubeconfig
        run: 'echo "$KUBECONFIG_CONTENT" > "$KUBECONFIG"'
        env:
          KUBECONFIG_CONTENT: ${{ secrets.DEPLOYMENT_KUBECONFIG }}
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      - name: Deploy to Live
        run: npx gulp deploy
        env:
          DEV_VERSION_NAME: pr-${{ github.event.number }}
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      - name: Delete Kubeconfig
        if: always()
        run: 'rm -f "$KUBECONFIG"'
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
