name: Teardown Dev

on:
  pull_request:
    types: [ closed ]

jobs:
  teardown:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      DEV_VERSION_NAME: pr-${{ github.event.number }}
      IMAGE: ghcr.io/studierlangsam/webseite:pr-${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3.2
        with:
          version: v1.23.1
      - name: Download npm Dependencies
        run: npm ci
      - name: Write Kubeconfig
        run: |
          echo "$KUBECONFIG_CONTENT" > "$KUBECONFIG"
        env:
          KUBECONFIG_CONTENT: ${{ secrets.DEPLOYMENT_KUBECONFIG }}
      - name: Teardown Dev Version
        run: |
          kubectl kustomize deployment/dev | 
            envsubst '$IMAGE $DEV_VERSION_NAME' | 
            kubectl delete -f -
      - name: Delete Kubeconfig
        if: always()
        run: |
          rm -f "$KUBECONFIG"
